### ISSUE TITLE
Add Tutorial/Setup page for VS Code + Cortex Debug

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyWiki#13]
Below is copy/pasted from my response on Slack

There isn't a specific official example yet. I've been trying to figure out a way to make VS Code projects for all of the Daisy Examples that can work from the root folder as a single workspace, but I don't know that it can work with how VS Code, and the extension are set up.
For now, if you have the DaisyExamples folder, you can pick any example and add the .vscode folder from this template. (I haven't used vs code for debugging in a few weeks. So I may have forgotten a step or two). I added a README to show what edits you have to make to the files (for the final binary, and the compiler path), but then you should be good to go.
I haven't tested this yet, but it came from a working project. I may have some time later today to test this, and I'll plan on making a wiki page specifically for this ASAP!

[CortexDebugFiles.zip](https://github.com/electro-smith/DaisyWiki/files/5455003/CortexDebugFiles.zip)

**Comment by stephenhensley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VS Code Tutorial Wiki Page](https://trello.com/c/jSOfQZkD/31-vs-code-tutorial-wiki-page)

**Comment by andrewikenberry** [comment]
We're going to go back to the original separate wiki page for installing Vs code and replacing the existing Getting Started page with that content as a starting point.

Ideal table of contents:

1. Get the Source

2. Install the Toolchain
2a. Install OpenOCD (Optional, only required for flashing over JTAG instead of USB)

3. Install the VS Code IDE
3a. Install Cortex Debug

4. Run the Blink Example 
4a. Flash Over USB
4b. Flash Over JTAG

5. Debugging

6. Troubleshooting

**Comment by stephenhensley** [comment]
added
