### ISSUE TITLE
exe does not exist

### ISSUE THREAD

**Issue by phil123456** [electro-smith/DaisyWiki#38]
hi

d2dsy_gui.exe is nowhere to be found

the link in the zip file will certainly not work since I have no **corvus** user

    C:\Users\corvus\Documents\GitHub\pd2dsy\dist\pd2dsyGUI\data\pd2dsy_gui.exe

do you even check what you upload ?

**Comment by CorvusPrudens** [comment]
Unfortunately, Windows shortcuts cannot be relative, so there isn't simple, portable way to make the exe easy to find. The obvious solution to this problem is to simply remove the shortcut, but the inelegance of that solution has us hesitating a bit. In the meantime, you can find the exe in the `data` folder. Of course, you can create your own shortcut and place it wherever you like.

**Comment by CorvusPrudens** [comment]
For clarity, the shortcut has been removed. If you're unsure of how to run the program, the README in its place should help out!
