### ISSUE TITLE
Problems extracting gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

### ISSUE THREAD

**Issue by JMLambert** [electro-smith/DaisyWiki#39]
When trying to extract to ~/Developer I get the following error during extraction:

"Could not create the hard link file:///home/user/Developer/libc.a"

Also, I'm trying to install V10.3 as suggested in the wiki, even though the page is listed as deprecated. I also noticed in other issue descriptions some folks are using a more recent version would there be a newer recommended version? I'm on Ubuntu 22.04.

Cheers :)

**Comment by takumi-ogata** [comment]
We sorted this out over email. The problem was a result of version 10.3 being used instead of 10.2 and older. 
I made this instruction clearer in the Wiki and also added the information about ignoring the "This page is deprecated" message on the GNU Arm Embedded Toolchain Downloads page. 

Thank you @JMLambert for bringing this up.
